### ISSUE TITLE
Plugin still sending empty and crashing if heat is unseeded during re-sync

### ISSUE THREAD

**Issue by vikibaarathi** [vikibaarathi/RH-Cloud-Link-Plugin#30]

**Comment by vikibaarathi** [comment]
Traceback (most recent call last):
  File "/home/director/RotorHazard/src/server/RHUtils.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/director/RotorHazard/src/server/eventmanager.py", line 101, in run_handler
    return handler(args)
  File "/home/director/RotorHazard/src/server/plugins/rhcloudlink/cloudlink.py", line 199, in heat_listener
    thisheat = self.getGroupingDetails(heat,db)
  File "/home/director/RotorHazard/src/server/plugins/rhcloudlink/cloudlink.py", line 254, in getGroupingDetails
    channel = racechannels[slot.node_index]
TypeError: list indices must be integers or slices, not NoneType

**Comment by vikibaarathi** [comment]
Resolved in #31
